/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SignIn;

import javax.swing.JOptionPane;
import libraryproject.Admin;

/**
 *
 * @author badawy
 */
public class Admin_Register extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Register
     */
    public Admin_Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jText_AdminId = new javax.swing.JTextField();
        jText_Adminpass = new javax.swing.JPasswordField();
        jButton_Adminsignin = new javax.swing.JButton();
        jButton_ADMINsigninback = new javax.swing.JButton();
        signIn = new javax.swing.JLabel();
        idl = new javax.swing.JLabel();
        Passwordl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Register");

        jButton_Adminsignin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton_Adminsignin.setForeground(new java.awt.Color(51, 153, 255));
        jButton_Adminsignin.setText("Sign In");
        jButton_Adminsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AdminsigninActionPerformed(evt);
            }
        });

        jButton_ADMINsigninback.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton_ADMINsigninback.setForeground(java.awt.Color.red);
        jButton_ADMINsigninback.setText("Back");
        jButton_ADMINsigninback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ADMINsigninbackActionPerformed(evt);
            }
        });

        signIn.setBackground(new java.awt.Color(255, 255, 255));
        signIn.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        signIn.setForeground(new java.awt.Color(0, 153, 255));
        signIn.setText("LOGIN ");

        idl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        idl.setText("User Name *");
        idl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                idlMousePressed(evt);
            }
        });

        Passwordl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Passwordl.setText("Password *");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idl)
                            .addComponent(signIn))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Passwordl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jText_AdminId, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                            .addComponent(jText_Adminpass))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Adminsignin, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_ADMINsigninback, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(signIn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(idl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_AdminId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Adminsignin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Passwordl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_Adminpass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ADMINsigninback, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AdminsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AdminsigninActionPerformed
       try{ 
        if(!jText_AdminId.getText().isEmpty()&& !jText_Adminpass.getText().isEmpty()){
               int id = Integer.parseInt(jText_AdminId.getText()) ;
               String pass=jText_Adminpass.getText();
           if(id==AdminStruct.Id&&pass.equals(AdminStruct.password)){
                 Admin a = new Admin();
                 a.setVisible(true);
                 this.setVisible(false);
               }
               else
                   JOptionPane.showMessageDialog(this, "Unvalid Id or Password");
          }
        else
            JOptionPane.showMessageDialog(this, "Unvalid Id or Password");
       }
       catch(Exception e){
            JOptionPane.showMessageDialog(this, "Unvalid Id or Password");
       }
    }//GEN-LAST:event_jButton_AdminsigninActionPerformed

    private void jButton_ADMINsigninbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ADMINsigninbackActionPerformed
        register a = new register();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton_ADMINsigninbackActionPerformed

    private void idlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idlMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_idlMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Passwordl;
    private javax.swing.JLabel idl;
    private javax.swing.JButton jButton_ADMINsigninback;
    private javax.swing.JButton jButton_Adminsignin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jText_AdminId;
    private javax.swing.JPasswordField jText_Adminpass;
    private javax.swing.JLabel signIn;
    // End of variables declaration//GEN-END:variables
}
