package user;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author compa
 */
import cart.editform;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import projectprototype.Manger;
 class x{
 
 };
public class searchgui extends javax.swing.JFrame {
     static Connection c;
     static Statement ss;
     static String query;
     static ResultSet r;

    /**
     * Creates new form searchgui
     */
    public searchgui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        img3 = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        img0 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        img4 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        img5 = new javax.swing.JLabel();
        name0 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        name3 = new javax.swing.JLabel();
        name4 = new javax.swing.JLabel();
        name5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Find Your BooK");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 156, -1, -1));

        jTextField1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jTextField1ComponentMoved(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextField1PropertyChange(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 223, 160, -1));

        img3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                img3MousePressed(evt);
            }
        });
        getContentPane().add(img3, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 382, 300, 300));

        img1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                img1MousePressed(evt);
            }
        });
        getContentPane().add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 29, 300, 300));

        img0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                img0MousePressed(evt);
            }
        });
        getContentPane().add(img0, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 29, 300, 300));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setForeground(new java.awt.Color(0, 153, 153));
        jButton1.setText("GO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 263, 115, -1));

        img4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                img4MousePressed(evt);
            }
        });
        getContentPane().add(img4, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 382, 300, 300));

        img2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                img2MousePressed(evt);
            }
        });
        getContentPane().add(img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 29, 300, 300));

        img5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                img5MousePressed(evt);
            }
        });
        getContentPane().add(img5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 382, 300, 300));

        name0.setText("name0");
        getContentPane().add(name0, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 342, 120, -1));

        name1.setText("name1");
        getContentPane().add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(879, 342, 163, -1));

        name2.setText("name2");
        getContentPane().add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1169, 342, 148, -1));

        name3.setText("name3");
        getContentPane().add(name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 689, 144, -1));

        name4.setText("name4");
        getContentPane().add(name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 689, 146, -1));

        name5.setText("name5");
        getContentPane().add(name5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1149, 689, 129, -1));

        jButton2.setBackground(new java.awt.Color(102, 255, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 657, 101, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTextField1ComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ComponentMoved

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
    
    }//GEN-LAST:event_jTextField1KeyTyped

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
 
    }//GEN-LAST:event_formWindowActivated

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
  String img = Manger.getBooks().get(0).getCoverUri();
  img0.setIcon(new ImageIcon(img));
  name0.setText(Manger.getBooks().get(0).getName());
  img = Manger.getBooks().get(1).getCoverUri();
  img1.setIcon(new ImageIcon(img));
  name1.setText(Manger.getBooks().get(1).getName());
  img = Manger.getBooks().get(2).getCoverUri();
  img2.setIcon(new ImageIcon(img));
  name2.setText(Manger.getBooks().get(2).getName());
   img = Manger.getBooks().get(3).getCoverUri();
  img3.setIcon(new ImageIcon(img));
  name3.setText(Manger.getBooks().get(3).getName());
        if (Manger.getBooks().size() == 5) {
         img = Manger.getBooks().get(4).getCoverUri();
  img4.setIcon(new ImageIcon(img));
  name4.setText(Manger.getBooks().get(4).getName());
        }
        else 
            name4.setVisible(false);
        if (Manger.getBooks().size() == 6) {
         img = Manger.getBooks().get(5).getCoverUri();
  img5.setIcon(new ImageIcon(img));
  name5.setText(Manger.getBooks().get(5).getName());
        }
         else 
            name5.setVisible(false);
  



    }//GEN-LAST:event_formWindowOpened

    private void jTextField1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextField1PropertyChange

      
    }//GEN-LAST:event_jTextField1PropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          System.out.println(jTextField1.getText());
        System.out.println(Manger.getBooks().get(0).getName().toLowerCase());
       
        System.out.println(jTextField1.getText().toLowerCase().contains(Manger.getBooks().get(0).getName().toLowerCase()));
        try{
        ArrayList <javax.swing.JLabel> imgs = new ArrayList();
        imgs.add(img0);
        imgs.add(img1);
        imgs.add(img2);
        imgs.add(img3);
        imgs.add(img4);
        imgs.add(img5);
                ArrayList <javax.swing.JLabel> names = new ArrayList();
names.add(name0);
        names.add(name1);
        names.add(name2);
        names.add(name3);
        names.add(name4);
        names.add(name5);
        String temp =jTextField1.getText();
        if (temp == ""){
        for (int i = 0 ; i<Manger.countArrayList();i++)
        {
            imgs.get(i).setVisible(true);
                        names.get(i).setVisible(true);

        }
        }
        else{
        int c=0;
        System.out.println("arry count 5555  " +Manger.countArrayList() );
        for (int i = 0 ; i<Manger.countArrayList();i++)
        {
            imgs.get(i).setVisible(false);
            names.get(i).setVisible(false);
         if((Manger.getBooks().get(i).getName().toLowerCase().contains(temp))){
                imgs.get(c).setIcon(new ImageIcon( Manger.getBooks().get(i).getCoverUri()));
                 names.get(c).setText( Manger.getBooks().get(i).getName());
                imgs.get(c).setVisible(true);
                names.get(c).setVisible(true);

                
              c++;  
             }
        
             
        }
        c=0;
                }

             
       
        }
        catch (Exception ee)
        {System.out.println(ee);}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void img0MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img0MousePressed

     String data=name0.getText();
        System.out.println(name0.getText());
     int id=returnName.returnid(data);
        System.out.println(id);
        enteredId.id= id;
     
editform e=new editform();
   e.setVisible(true);
   this.setVisible(false);


        // TODO add your handling code here:
    }//GEN-LAST:event_img0MousePressed

    private void img1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img1MousePressed
 String data=name1.getText();
     int id=returnName.returnid(data);
        System.out.println(id);
        // TODO add your handling code here:
         enteredId.id= id;
         editform e=new editform();
   e.setVisible(true);
   this.setVisible(false);
    }//GEN-LAST:event_img1MousePressed

    private void img2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img2MousePressed
String data=name2.getText();
     int id=returnName.returnid(data);
      enteredId.id= id;
        System.out.println(id);      
        editform e=new editform();
   e.setVisible(true);
   this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_img2MousePressed

    private void img3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img3MousePressed
String data=name3.getText();
     int id=returnName.returnid(data);
      enteredId.id= id;
        System.out.println(id);   
        editform e=new editform();
   e.setVisible(true);
   this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_img3MousePressed

    private void img4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img4MousePressed
String data=name4.getText();
     int id=returnName.returnid(data);
      enteredId.id= id;
        System.out.println(id); 
        editform e=new editform();
   e.setVisible(true);
   this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_img4MousePressed

    private void img5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img5MousePressed
String data=name5.getText();
     int id=returnName.returnid(data);
      enteredId.id= id;
        System.out.println(id);    
        editform e=new editform();
   e.setVisible(true);
   this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_img5MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this. setVisible(false);
userwindow x =new userwindow();
x.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchgui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img0;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel img4;
    private javax.swing.JLabel img5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel name0;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel name5;
    // End of variables declaration//GEN-END:variables


}
