
package edit;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javaapplication9.mainClasses.Book;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import projectprototype.Connec;


/**
 *
 * @author mahmo
 */
public class editform extends javax.swing.JFrame {
   static Connection c,c1;
  static Statement s,s1;
  static String modify;
  static ResultSet r;
   
    public editform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        author = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cost = new javax.swing.JLabel();
        discount = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nameClick = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        descriptionclick = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        count = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        url = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cover = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("EDIT BOOK");

        name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(102, 102, 102));
        name.setText("name label");
        name.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                nameComponentShown(evt);
            }
        });
        name.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                namePropertyChange(evt);
            }
        });

        author.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        author.setForeground(new java.awt.Color(102, 102, 102));
        author.setText("author ");
        author.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                authorPropertyChange(evt);
            }
        });

        cost.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cost.setForeground(new java.awt.Color(102, 102, 102));
        cost.setText("COST");
        cost.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                costPropertyChange(evt);
            }
        });

        discount.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        discount.setForeground(new java.awt.Color(102, 102, 102));
        discount.setText("NEW DISCOUNT");
        discount.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                discountPropertyChange(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(java.awt.Color.red);
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        nameClick.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        nameClick.setText("NAME");
        nameClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nameClickMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("AUTHOR");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });

        descriptionclick.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        descriptionclick.setText("DESCRIPTION");
        descriptionclick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descriptionclickMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("COST");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("DISCOUNT");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });

        count.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        count.setForeground(new java.awt.Color(102, 102, 102));
        count.setText("count");
        count.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                countPropertyChange(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Count");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });

        description.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        description.setForeground(new java.awt.Color(102, 102, 102));
        description.setText("description");
        description.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                descriptionMouseMoved(evt);
            }
        });
        description.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                descriptionComponentShown(evt);
            }
        });
        description.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                descriptionPropertyChange(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("URL");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        url.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        url.setForeground(new java.awt.Color(102, 102, 102));
        url.setText("URL");
        url.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                urlPropertyChange(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Cover");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        cover.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cover.setForeground(new java.awt.Color(102, 102, 102));
        cover.setText("coveruri");
        cover.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                coverPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(866, 866, 866)
                .addComponent(jLabel6))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameClick, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(descriptionclick)
                            .addComponent(jLabel12))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(description)
                                .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(url)
                                    .addComponent(cover)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(count))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(discount))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descriptionclick, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(82, 82, 82))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameClick, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name)
                            .addComponent(jLabel15)
                            .addComponent(count))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(discount))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(url)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cover)
                            .addComponent(jLabel12)
                            .addComponent(cost))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_nameComponentShown
        String m;

      Connec k=new Connec();
       try{
     c=  k.connect();
     s=c.createStatement();
   modify="select * from book";
    r= s.executeQuery(modify);
    for(int i=0;i<enteredId.id;i++)
    {     r.next();    }
    m=r.getString("name");
    name.setText(m);
      
    }
    catch(SQLException x)
    {
        System.out.println(x.getMessage());
    }
    }//GEN-LAST:event_nameComponentShown

    private void namePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_namePropertyChange
                     String m;

        Connec k=new Connec();
       try{
     c=  k.connect();
     s=c.createStatement();
   modify="select * from book";
    r= s.executeQuery(modify);
    for(int i=0;i<enteredId.id;i++)
    {     r.next();    }
    m=r.getString("name");
    name.setText(m);
      
    }
    catch(SQLException x)
    {
        System.out.println(x.getMessage());
    }
    }//GEN-LAST:event_namePropertyChange

    private void authorPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_authorPropertyChange
        String data=getfromdata("auther");
        author.setText(data);
    }//GEN-LAST:event_authorPropertyChange

    private void costPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_costPropertyChange
        String data=getfromdata("cost");
        cost.setText(data);
    }//GEN-LAST:event_costPropertyChange

    private void discountPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_discountPropertyChange
        String data= getfromdata("discound");
        discount.setText(data);
    }//GEN-LAST:event_discountPropertyChange

    private void nameClickMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameClickMousePressed
        Book b =new Book();
        String m;
        Connec k=new Connec();
        String newname;
        newname= JOptionPane.showInputDialog("Enter New Name"); 
    try{ 
         c=  k.connect();
        s=c.createStatement();
        modify="update book set name ='"+newname+"'where id='"+enteredId.id+"'";
         s.execute(modify);
          name.setText(newname);
    }
    catch(SQLException e1)
    {
    
        
        System.out.println(e1.getMessage());   
    }
      

       
  
    }//GEN-LAST:event_nameClickMousePressed

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        String newauthor=JOptionPane.showInputDialog("Enter New Author");
        updateauthor(newauthor);
        author.setText(newauthor);
    }//GEN-LAST:event_jLabel10MousePressed

    private void descriptionclickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descriptionclickMouseClicked
       String newdescription=JOptionPane.showInputDialog(this, "Enter new Description");
       modify="update book set description='"+newdescription+"' where id ='"+enteredId.id+"'";
       try{s.execute(modify);}
       catch(SQLException b)
       {
           JOptionPane.showConfirmDialog(this,b.getMessage());
       }
       description.setText(newdescription);
    }//GEN-LAST:event_descriptionclickMouseClicked

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        String newdata=JOptionPane.showInputDialog("Enter New Cost");
        updatecost(newdata);
        cost.setText(newdata);
    }//GEN-LAST:event_jLabel12MousePressed

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        String ddata= JOptionPane.showInputDialog("Enter new Discount");
        updatediscount(ddata);
        discount.setText(ddata);
    }//GEN-LAST:event_jLabel13MousePressed

    private void countPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_countPropertyChange
        count.setText(getfromdata("booknum"));
    }//GEN-LAST:event_countPropertyChange

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
        String newdata= JOptionPane.showInputDialog("Enter New number of copies");
        updatebookcopy(newdata);
        count.setText(newdata);
    }//GEN-LAST:event_jLabel15MousePressed

    private void descriptionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descriptionMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionMouseMoved

    private void descriptionComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_descriptionComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionComponentShown

    private void descriptionPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_descriptionPropertyChange
                  String m;

     Connec k = new Connec();
       try{
     c=  k.connect();
     s=c.createStatement();
   modify="select * from book";
    r= s.executeQuery(modify);
    for(int i=0;i<enteredId.id;i++)
    {     r.next();    }
    m=r.getString("description");
    description.setText(m);
      
    }
    catch(SQLException x)
    {
        System.out.println(x.getMessage());
    }
        
    }                                          
public String getfromdata (String column)
{
    String data="";
  try{  modify="select * from book";
    r= s.executeQuery(modify);
    for(int i=0;i<enteredId.id;i++)
    {     r.next();    }
   data=r.getString(column);
   return data;
  }
  catch(SQLException b)
  {
      JOptionPane.showConfirmDialog(this,b.getMessage());
  }
  return data;
    }//GEN-LAST:event_descriptionPropertyChange

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        String newdata=JOptionPane.showInputDialog("Enter New Website of book");
        updateurl(newdata);
        url.setText(newdata);
    }//GEN-LAST:event_jLabel2MousePressed

    private void urlPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_urlPropertyChange
        String cn=getfromdata("url");
        url.setText(cn);
    }//GEN-LAST:event_urlPropertyChange

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        String newdata=JOptionPane.showInputDialog("Enter New Address of BookCover");
        updatecoveruri(newdata);
        cover.setText(newdata);
    }//GEN-LAST:event_jLabel3MousePressed

    private void coverPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_coverPropertyChange
        String bn=getfromdata("coverUri");
        cover.setText(bn);
    }//GEN-LAST:event_coverPropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        idbeforeedit a = new idbeforeedit();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

public void updatecoveruri(String newdata) {
   
     try{ 
   modify="update book set coverUri='"+newdata+"'where id ='"+enteredId.id+"' ";
   s.execute(modify);
   
    }
    catch(SQLException e1)
    {
    
        
        JOptionPane.showMessageDialog(this,e1.getMessage());
    
    }
    
}
public void updateurl(String newdata) {
   
     try{ 
   modify="update book set url='"+newdata+"'where id ='"+enteredId.id+"' ";
   s.execute(modify);
   
    }
    catch(SQLException e1)
    {
    
        
        JOptionPane.showMessageDialog(this,e1.getMessage());
    
    }
    
}
public void updatebookcopy(String newdata) {
   
     try{ 
   modify="update book set booknum='"+newdata+"'where id ='"+enteredId.id+"' ";
   s.execute(modify);
   
    }
    catch(SQLException e1)
    {
    
        
        JOptionPane.showMessageDialog(this,e1.getMessage());
    
    }
    
}
public void updatediscount(String newdata) {
   
     try{ 
   modify="update book set discound='"+newdata+"'where id ='"+enteredId.id+"' ";
   s.execute(modify);
   
    }
    catch(SQLException e1)
    {
    
        
        JOptionPane.showMessageDialog(this,e1.getMessage());
    
    }
    
}
public void updatecost(String newdata) {
   
     try{ 
   modify="update book set cost='"+newdata+"'where id ='"+enteredId.id+"' ";
   s.execute(modify);
   
    }
    catch(SQLException e1)
    {
    
        
        JOptionPane.showMessageDialog(this,e1.getMessage());
    
    }
    
}
public void updateauthor(String newdata) {
   
     try{ 
   modify="update book set auther='"+newdata+"'where id ='"+enteredId.id+"' ";
   s.execute(modify);
   
    }
    catch(SQLException e1)
    {
    
        
        JOptionPane.showMessageDialog(this,e1.getMessage());
    
    }
    
}
   
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel author;
    private javax.swing.JLabel cost;
    private javax.swing.JLabel count;
    private javax.swing.JLabel cover;
    private javax.swing.JLabel description;
    private javax.swing.JLabel descriptionclick;
    private javax.swing.JLabel discount;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nameClick;
    private javax.swing.JLabel url;
    // End of variables declaration//GEN-END:variables
}
