package cart;


import java.util.ArrayList;
import javaapplication9.mainClasses.Book;
import javaapplication9.userId;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import projectprototype.*;
import user.userwindow;
/**
 *
 * @author compa
 */
public class DisplayBooks extends javax.swing.JFrame {
    static int uId = userId.id;
    static ArrayList <Users> usrs = new ArrayList();
    static ArrayList <Integer> bookslib = new ArrayList();
    static ArrayList <Book>booksmanger=new ArrayList();
    static int cost=0;
    /**
     * Creates new form DisplayBooks
     */
    public DisplayBooks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img0 = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        img4 = new javax.swing.JLabel();
        img5 = new javax.swing.JLabel();
        delete0 = new javax.swing.JButton();
        delete1 = new javax.swing.JButton();
        delete2 = new javax.swing.JButton();
        delete3 = new javax.swing.JButton();
        delete4 = new javax.swing.JButton();
        delete5 = new javax.swing.JButton();
        totalcost = new javax.swing.JLabel();
        showtotalcost = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(img0, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 13, 274, 239));
        img0.getAccessibleContext().setAccessibleName("img0");

        getContentPane().add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 13, 274, 239));
        getContentPane().add(img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 13, 274, 239));
        getContentPane().add(img3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 406, 274, 239));
        getContentPane().add(img4, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 406, 274, 239));
        getContentPane().add(img5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 410, 274, 239));

        delete0.setBackground(new java.awt.Color(51, 204, 255));
        delete0.setFont(new java.awt.Font("Vineta BT", 0, 12)); // NOI18N
        delete0.setForeground(new java.awt.Color(255, 51, 51));
        delete0.setText("Delete ");
        delete0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete0ActionPerformed(evt);
            }
        });
        getContentPane().add(delete0, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 290, -1, -1));

        delete1.setBackground(new java.awt.Color(51, 204, 255));
        delete1.setFont(new java.awt.Font("Vineta BT", 3, 12)); // NOI18N
        delete1.setForeground(new java.awt.Color(255, 0, 51));
        delete1.setText("Delete");
        delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ActionPerformed(evt);
            }
        });
        getContentPane().add(delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, -1, -1));

        delete2.setBackground(new java.awt.Color(0, 204, 255));
        delete2.setFont(new java.awt.Font("Vineta BT", 0, 12)); // NOI18N
        delete2.setForeground(new java.awt.Color(255, 0, 102));
        delete2.setText("Delete");
        delete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete2ActionPerformed(evt);
            }
        });
        getContentPane().add(delete2, new org.netbeans.lib.awtextra.AbsoluteConstraints(857, 290, -1, -1));

        delete3.setBackground(new java.awt.Color(51, 204, 255));
        delete3.setFont(new java.awt.Font("Vineta BT", 3, 12)); // NOI18N
        delete3.setForeground(new java.awt.Color(255, 51, 51));
        delete3.setText("Delete");
        delete3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete3ActionPerformed(evt);
            }
        });
        getContentPane().add(delete3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 670, 94, -1));

        delete4.setBackground(new java.awt.Color(51, 255, 255));
        delete4.setFont(new java.awt.Font("Vineta BT", 3, 12)); // NOI18N
        delete4.setForeground(new java.awt.Color(255, 0, 0));
        delete4.setText("Delete");
        delete4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete4ActionPerformed(evt);
            }
        });
        getContentPane().add(delete4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 670, -1, -1));

        delete5.setBackground(new java.awt.Color(51, 204, 255));
        delete5.setFont(new java.awt.Font("Vineta BT", 3, 12)); // NOI18N
        delete5.setForeground(new java.awt.Color(255, 0, 102));
        delete5.setText("Delete");
        delete5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete5ActionPerformed(evt);
            }
        });
        getContentPane().add(delete5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 670, -1, -1));

        totalcost.setFont(new java.awt.Font("Swis721 Blk BT", 3, 18)); // NOI18N
        totalcost.setForeground(new java.awt.Color(255, 0, 102));
        totalcost.setText("Total Cost");
        getContentPane().add(totalcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 111, 33));
        getContentPane().add(showtotalcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 102, 28));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setForeground(new java.awt.Color(102, 255, 0));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
ArrayList <javax.swing.JLabel> imgs = new ArrayList();
ArrayList <javax.swing.JButton> delete = new ArrayList();
bookslib = UsersManger.displayBooks(uId);
booksmanger = Manger.getBooks();
ArrayList <Integer> books = new ArrayList();

books =  UsersManger.displayBooks(uId);  
        imgs.add(img0);
        imgs.add(img1);
        imgs.add(img2);
        imgs.add(img3);
        imgs.add(img4);
        imgs.add(img5);
        
        delete.add(delete0); 
         delete.add(delete1);
          delete.add(delete2);
           delete.add(delete3);
            delete.add(delete4);
             delete.add(delete5);
    for (int i=0; i <imgs.size();i++){
                    imgs.get(i).setVisible(false);

    }
              delete.add(delete5);
    for (int i=0; i <delete.size();i++){
                    delete.get(i).setVisible(false);

    }
   
    System.out.println(books);
/*
  for (int i=0; i <books.size();i++){
      
                imgs.get(i).setIcon(new ImageIcon( Manger.getBooks().get(books.get(i)-1).getCoverUri()));
                imgs.get(i).setVisible(true);
                delete.get(i).setVisible(true);

                System.out.println(books.get(i));
                cost += Manger.getBooks().get(books.get(i)-1).getCost();
                
 }
    showtotalcost.setText(String.valueOf(cost));
    cost=0;
    */
for (int i=0; i <bookslib.size();i++){
      
                imgs.get(i).setIcon(new ImageIcon( booksmanger.get(bookslib.get(i)-1).getCoverUri()));
                imgs.get(i).setVisible(true);
                delete.get(i).setVisible(true);

                System.out.println(books.get(i));
                cost += booksmanger.get(bookslib.get(i)-1).getCost();
                
 }
    showtotalcost.setText(String.valueOf(cost));
    cost=0;
    }//GEN-LAST:event_formWindowOpened

    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed
        img1.setVisible(false);
        delete1.setVisible(false);
             ArrayList <Integer> sk1 = new ArrayList();
        sk1=bookslib;
        ArrayList <Book> sk2 = new ArrayList();
        sk2=booksmanger;
        sk1.remove(bookslib.get(1));
        for (int i =0;i<sk1.size();i++){
             cost += sk2.get(sk1.get(i)-1).getCost();     
}       bookslib.remove(1);
         showtotalcost.setText(String.valueOf(cost));
         cost=0;
         
         
        
        int UsersBook =UsersManger.displayBooks(uId).get(1);
        UsersManger.addBookCount(UsersBook);
        UsersManger.deleteBooks(uId, UsersBook);
        JOptionPane.showMessageDialog(this,"Book Successfully deleted");
     
        }//GEN-LAST:event_delete1ActionPerformed

    private void delete0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete0ActionPerformed
         img0.setVisible(false);
        delete0.setVisible(false);
        ArrayList <Integer> sk1 = new ArrayList();
        sk1=bookslib;
        ArrayList <Book> sk2 = new ArrayList();
        sk2=booksmanger;
        sk1.remove(bookslib.get(0));
        for (int i =0;i<sk1.size();i++){
             cost += sk2.get(sk1.get(i)-1).getCost();     
}
         showtotalcost.setText(String.valueOf(cost));
         cost=0;
        
        
        
        int UsersBook =UsersManger.displayBooks(uId).get(0);
        UsersManger.addBookCount(UsersBook);
        UsersManger.deleteBooks(uId, UsersBook);
        JOptionPane.showMessageDialog(this,"Book Successfully deleted");
         }//GEN-LAST:event_delete0ActionPerformed

    private void delete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete2ActionPerformed
        img2.setVisible(false);
        delete2.setVisible(false);
        
         ArrayList <Integer> sk1 = new ArrayList();
        sk1=bookslib;
        ArrayList <Book> sk2 = new ArrayList();
        sk2=booksmanger;
        sk1.remove(bookslib.get(2));
        for (int i =0;i<sk1.size();i++){
             cost += sk2.get(sk1.get(i)-1).getCost();     
}
         showtotalcost.setText(String.valueOf(cost));
         cost=0;
        int UsersBook =UsersManger.displayBooks(uId).get(2);
        UsersManger.addBookCount(UsersBook);
        UsersManger.deleteBooks(uId, UsersBook);
        JOptionPane.showMessageDialog(this,"Book Successfully deleted");
         }//GEN-LAST:event_delete2ActionPerformed

    private void delete3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete3ActionPerformed
        img3.setVisible(false);
        delete3.setVisible(false);
        
         ArrayList <Integer> sk1 = new ArrayList();
        sk1=bookslib;
        ArrayList <Book> sk2 = new ArrayList();
        sk2=booksmanger;
        sk1.remove(bookslib.get(3));
        for (int i =0;i<sk1.size();i++){
             cost += sk2.get(sk1.get(i)-1).getCost();     
}
         showtotalcost.setText(String.valueOf(cost));
         cost=0;
        int UsersBook =UsersManger.displayBooks(uId).get(3);
        UsersManger.addBookCount(UsersBook);
        UsersManger.deleteBooks(uId, UsersBook);
        JOptionPane.showMessageDialog(this,"Book Successfully deleted");
         }//GEN-LAST:event_delete3ActionPerformed

    private void delete4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete4ActionPerformed
        img4.setVisible(false);
        delete4.setVisible(false);
        
         ArrayList <Integer> sk1 = new ArrayList();
        sk1=bookslib;
        ArrayList <Book> sk2 = new ArrayList();
        sk2=booksmanger;
        sk1.remove(bookslib.get(4));
        for (int i =0;i<sk1.size();i++){
             cost += sk2.get(sk1.get(i)-1).getCost();     
}
         showtotalcost.setText(String.valueOf(cost));
         cost=0;
        int UsersBook =UsersManger.displayBooks(uId).get(4);
        UsersManger.addBookCount(UsersBook);
        UsersManger.deleteBooks(uId, UsersBook);
        JOptionPane.showMessageDialog(this,"Book Successfully deleted");
         }//GEN-LAST:event_delete4ActionPerformed

    private void delete5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete5ActionPerformed
       img5.setVisible(false);
        delete5.setVisible(false);
         ArrayList <Integer> sk1 = new ArrayList();
        sk1=bookslib;
        ArrayList <Book> sk2 = new ArrayList();
        sk2=booksmanger;
        sk1.remove(bookslib.get(5));
        for (int i =0;i<sk1.size();i++){
             cost += sk2.get(sk1.get(i)-1).getCost();     
}
         showtotalcost.setText(String.valueOf(cost));
         cost=0;
        int UsersBook =UsersManger.displayBooks(uId).get(5);
        UsersManger.addBookCount(UsersBook);
        UsersManger.deleteBooks(uId, UsersBook);
        JOptionPane.showMessageDialog(this,"Book Successfully deleted");
         }//GEN-LAST:event_delete5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.setVisible(false);
        userwindow x = new userwindow();
        x.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete0;
    private javax.swing.JButton delete1;
    private javax.swing.JButton delete2;
    private javax.swing.JButton delete3;
    private javax.swing.JButton delete4;
    private javax.swing.JButton delete5;
    private javax.swing.JLabel img0;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel img4;
    private javax.swing.JLabel img5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel showtotalcost;
    private javax.swing.JLabel totalcost;
    // End of variables declaration//GEN-END:variables
}
