/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cart;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javaapplication9.userId;
import javax.swing.JOptionPane;
import projectprototype.Connec;
import projectprototype.UsersManger;
import user.enteredId;
import user.searchgui;


/**
 *
 * @author mahmo
 */
public class editform extends javax.swing.JFrame {
   static Connection c,c1;
  static Statement s,s1;
  static String modify;
  static ResultSet r;
   
    public editform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        author = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cost = new javax.swing.JLabel();
        discount = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nameClick = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        descriptionclick = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        count = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        url = new javax.swing.JLabel();
        uri = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setForeground(new java.awt.Color(51, 204, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 231, 58));

        name.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("name label");
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nameMousePressed(evt);
            }
        });
        name.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                nameComponentShown(evt);
            }
        });
        name.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                namePropertyChange(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 143, 21));

        author.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        author.setForeground(new java.awt.Color(255, 255, 255));
        author.setText("author ");
        author.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                authorPropertyChange(evt);
            }
        });
        jPanel1.add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 99, 22));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 478, -1, -1));

        cost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cost.setForeground(new java.awt.Color(255, 255, 255));
        cost.setText("COST");
        cost.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                costPropertyChange(evt);
            }
        });
        jPanel1.add(cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 152, -1));

        discount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        discount.setForeground(new java.awt.Color(255, 255, 255));
        discount.setText("NEW DISCOUNT");
        discount.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                discountPropertyChange(evt);
            }
        });
        jPanel1.add(discount, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Sitka Heading", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Add to cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 130, 47));

        nameClick.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        nameClick.setForeground(new java.awt.Color(255, 255, 255));
        nameClick.setText("NAME");
        nameClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nameClickMousePressed(evt);
            }
        });
        jPanel1.add(nameClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 80, 35));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("AUTHOR");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 100, -1));

        descriptionclick.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        descriptionclick.setForeground(new java.awt.Color(255, 255, 255));
        descriptionclick.setText("DESCRIPTION");
        descriptionclick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descriptionclickMouseClicked(evt);
            }
        });
        jPanel1.add(descriptionclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, 26));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("COST");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("DISCOUNT");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 110, -1));

        count.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        count.setForeground(new java.awt.Color(255, 255, 255));
        count.setText("count");
        count.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                countPropertyChange(evt);
            }
        });
        jPanel1.add(count, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Count");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        description.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        description.setForeground(new java.awt.Color(255, 255, 255));
        description.setText("description");
        description.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                descriptionMouseMoved(evt);
            }
        });
        description.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                descriptionComponentShown(evt);
            }
        });
        description.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                descriptionPropertyChange(evt);
            }
        });
        jPanel1.add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 176, 43));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("URL");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 70, 30));

        url.setBackground(new java.awt.Color(255, 255, 255));
        url.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        url.setForeground(new java.awt.Color(255, 255, 255));
        url.setText("URL");
        url.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                urlPropertyChange(evt);
            }
        });
        jPanel1.add(url, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, -1, -1));

        uri.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                uriPropertyChange(evt);
            }
        });
        jPanel1.add(uri, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 129, 160, 336));

        Back.setBackground(new java.awt.Color(102, 102, 102));
        Back.setFont(new java.awt.Font("Showcard Gothic", 3, 18)); // NOI18N
        Back.setForeground(new java.awt.Color(0, 204, 102));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 110, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cart/free-book-library.jpg"))); // NOI18N
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameClickMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameClickMousePressed
      
      
  
    }//GEN-LAST:event_nameClickMousePressed

    private void nameComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_nameComponentShown
     
      
   
      
        
    }//GEN-LAST:event_nameComponentShown

    private void namePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_namePropertyChange
               String m;

        Connec k=new Connec();
       try{
     c=  k.connect();
     s=c.createStatement();
   modify="select * from book";
    r= s.executeQuery(modify);
    for(int i=0;i<enteredId.id;i++)
    {     r.next();    }
    m=r.getString("name");
    name.setText(m);
      
    }
    catch(SQLException x)
    {
        System.out.println(x.getMessage());
    }
    }//GEN-LAST:event_namePropertyChange

    private void descriptionComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_descriptionComponentShown
    
//      String m;
//      try{
//
//     s=c.createStatement();
//   modify="select * from book";
//    r= s.executeQuery(modify);
//    for(int i=0;i<enteredId.id;i++)
//    {     r.next();    }
//    m=r.getString("description");
//    description.setText(m);
//      
//    }
//    catch(SQLException x)
//    {
//        System.out.println(x.getMessage());
//    }
    }//GEN-LAST:event_descriptionComponentShown

    private void descriptionPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_descriptionPropertyChange
          String m;

        Connec k=new Connec();
       try{
     c=  k.connect();
     s=c.createStatement();
   modify="select * from book";
    r= s.executeQuery(modify);
    for(int i=0;i<enteredId.id;i++)
    {     r.next();    }
    m=r.getString("description");
    description.setText(m);
      
    }
    catch(SQLException x)
    {
        System.out.println(x.getMessage());
    }
        
    }//GEN-LAST:event_descriptionPropertyChange
public String getfromdata (String column)
{
    String data="";
  try{  modify="select * from book";
    r= s.executeQuery(modify);
    for(int i=0;i<enteredId.id;i++)
    {     r.next();    }
   data=r.getString(column);
   return data;
  }
  catch(SQLException b)
  {
      JOptionPane.showConfirmDialog(this,b.getMessage());
  }
  return data;
}
public void updatecoveruri(String newdata) {
   
     try{ 
   modify="update book set coverUri='"+newdata+"'where id ='"+enteredId.id+"' ";
   s.execute(modify);
   
    }
    catch(SQLException e1)
    {
    
        
        JOptionPane.showMessageDialog(this,e1.getMessage());
    
    }
    
}
public void updateurl(String newdata) {
   
     try{ 
   modify="update book set url='"+newdata+"'where id ='"+enteredId.id+"' ";
   s.execute(modify);
   
    }
    catch(SQLException e1)
    {
    
        
        JOptionPane.showMessageDialog(this,e1.getMessage());
    
    }
    
}
public void updatebookcopy(String newdata) {
   
     try{ 
   modify="update book set booknum='"+newdata+"'where id ='"+enteredId.id+"' ";
   s.execute(modify);
   
    }
    catch(SQLException e1)
    {
    
        
        JOptionPane.showMessageDialog(this,e1.getMessage());
    
    }
    
}
public void updatediscount(String newdata) {
   
     try{ 
   modify="update book set discound='"+newdata+"'where id ='"+enteredId.id+"' ";
   s.execute(modify);
   
    }
    catch(SQLException e1)
    {
    
        
        JOptionPane.showMessageDialog(this,e1.getMessage());
    
    }
    
}
public void updatecost(String newdata) {
   
     try{ 
   modify="update book set cost='"+newdata+"'where id ='"+enteredId.id+"' ";
   s.execute(modify);
   
    }
    catch(SQLException e1)
    {
    
        
        JOptionPane.showMessageDialog(this,e1.getMessage());
    
    }
    
}
public void updateauthor(String newdata) {
   
     try{ 
   modify="update book set auther='"+newdata+"'where id ='"+enteredId.id+"' ";
   s.execute(modify);
   
    }
    catch(SQLException e1)
    {
    
        
        JOptionPane.showMessageDialog(this,e1.getMessage());
    
    }
    
}
    private void descriptionclickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descriptionclickMouseClicked
      
    }//GEN-LAST:event_descriptionclickMouseClicked

    private void authorPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_authorPropertyChange
     String data=getfromdata("auther");
    author.setText(data);
         
    }//GEN-LAST:event_authorPropertyChange

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
       
        
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MousePressed

    private void costPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_costPropertyChange
      
        String data=getfromdata("cost");
        cost.setText(data);
        
    }//GEN-LAST:event_costPropertyChange

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
       
    }//GEN-LAST:event_jLabel12MousePressed

    private void countPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_countPropertyChange
    
         count.setText(getfromdata("booknum"));
        
    }//GEN-LAST:event_countPropertyChange

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
     
    }//GEN-LAST:event_jLabel15MousePressed

    private void discountPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_discountPropertyChange
        
      String data= getfromdata("discound");
 discount.setText(data);
    }//GEN-LAST:event_discountPropertyChange

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
  
    }//GEN-LAST:event_jLabel13MousePressed

    private void descriptionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descriptionMouseMoved

                // TODO add your handling code here:
    }//GEN-LAST:event_descriptionMouseMoved

    private void urlPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_urlPropertyChange
       String cn=getfromdata("url");
       url.setText(cn);
       
        // TODO add your handling code here:
    }//GEN-LAST:event_urlPropertyChange

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        
    }//GEN-LAST:event_jLabel2MousePressed

    private void uriPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_uriPropertyChange
       
    }//GEN-LAST:event_uriPropertyChange

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
this.setVisible(false);
        searchgui x= new searchgui();
x.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      int uId= userId.id ;
   
     int bookId=enteredId.id;
       String library = UsersManger.getUser().get(uId-1).getLibrary();
     boolean nullChecker = (library == null || library.length() == 0);
     if (!(UsersManger.checkBookStock(bookId))){
     JOptionPane.showMessageDialog(null, "The book you selected is currently out of stock", "Error", JOptionPane.ERROR_MESSAGE);
             }
         else{
     if (nullChecker){
         
     String lib = Integer.toString(bookId);
     UsersManger.writeToLibrary(uId,lib);
     UsersManger.changeCount(bookId);
     JOptionPane.showMessageDialog(this,"Book Successfully added to your cart");

     }
     else if((library.contains(Integer.toString(bookId)))){
     JOptionPane.showMessageDialog(null, "This book already exists in your cart", "Error", JOptionPane.ERROR_MESSAGE);
     } 
     else {
     String lib =UsersManger.getUser().get(uId-1).getLibrary()+','+bookId;
     UsersManger.writeToLibrary(uId,lib);
     UsersManger.changeCount(bookId);
     JOptionPane.showMessageDialog(this,"Book Successfully added to your cart");   
    
     }
     }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameMousePressed

   
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel author;
    private javax.swing.JLabel cost;
    private javax.swing.JLabel count;
    private javax.swing.JLabel description;
    private javax.swing.JLabel descriptionclick;
    private javax.swing.JLabel discount;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nameClick;
    private javax.swing.JLabel uri;
    private javax.swing.JLabel url;
    // End of variables declaration//GEN-END:variables
}
